---
title: "worldunirank"
output: html_document
---

```{r}
#install.packages("ggplot2")
#install.packages("dplyr")

library(ggplot2)
library(dplyr)
library(readxl)

```

Гендерне питання у світових університетах: Японія, США, Велика Британія

```{r}

worldunirank <- read_excel("D:/Медіакомунікації/Візуалізація даних/worldunirank.xlsx")
View(worldunirank)

data(package="worldunirank")

worldunirank <- tbl_df(worldunirank) 

```

Відсортуєпо потрібні дані по Японії

```{r}
df <- worldunirank

df %>% 
  filter(Country == "Japan")%>%
  select("University_Name", "%_Female_Students", "Year") %>% View()

df1 <- df %>%                                    #створюємо нову змінну
  filter(Country == "Japan")%>%
  select("University_Name", "%_Female_Students", "Year") 


    
```
Графіки

```{r}
df1 %>%
  ggplot(aes("University_Name","%_Female_Students", colour=Year))+
  geom_point(alpha = 0.5, size = .75) 


df1 %>%
ggplot(aes(x= "University_Name", "%_Female_Students")) + 
  geom_histogram(breaks=seq(20, 50, by=2), 
                 col="red", 
                 fill="green", 
                 alpha = .2)
```

```{r}
df %>% 
  filter(Country == "United States of America")%>%
  select("University_Name", "%_Female_Students", "Year")%>% View()





```


